### ISSUE TITLE
Lambdas not bein' generated in lambdas/

### ISSUE THREAD

**Issue by chazu** [articulate/jarbs#1]
```
npm WARN EPACKAGEJSON resizer@0.0.0 No description
Generating function skeleton at lambdas/resizer
Function description: Generic image resizing lambda
┐ (Chazu@Nono) [14:25:21|Wed Nov 04] [~/articulate/jarbs-fake]
└───> ls lambdas/resizer
ls: lambdas/resizer: No such file or directory
┐ (Chazu@Nono) [14:25:31|Wed Nov 04] [~/articulate/jarbs-fake]
└───> ls
resizer
┐ (Chazu@Nono) [14:25:33|Wed Nov 04] [~/articulate/jarbs-fake]
└───> cowsay lolwat
 ________
< lolwat >
 --------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
┐ (Chazu@Nono) [14:28:12|Wed Nov 04] [~/articulate/jarbs-fake]
└───>
```

**Comment by chazu** [comment]
I trust that Bessie's presentation above sufficiently illustrates the issue? :trollface:

**Comment by plukevdh** [comment]
Get me a `jarbs -v`?

**Comment by chazu** [comment]
0.5.0 - So the issue here isn't exactly what I thought - because ~/articulate/jarbs-fake doesn't have a lambdas/ dir, i guess that 'lambda new <x>' thinks its creating a new _project_? In other words, 'jarbs new' multiplexes two features - project init and lambda scaffolding, is this correct? I found this confusing, myself - have you considered doing something like 'jarbs generate <thing> <name> <opts>' for scaffolding, or just separating out 'jarbs init' for projects and 'jarbs new' for lambdas/other AWS thingies?

**Comment by plukevdh** [comment]
Closed by discussion elsewhere.
