### ISSUE TITLE
Feature Request - Build to zip file

### ISSUE THREAD

**Issue by chazu** [articulate/jarbs#15]
In order to facilitate usage with terraform's lambda resource, it would be nice to have a command which would build to the point of zipping the lambda(s) and placing them somewhere to be used with terraform.

**Comment by plukevdh** [comment]
This exists using the `--debug` flag, though it will also still run the deployment.

**Comment by chazu** [comment]
Dis is oooooold and I ain't used jarbs in ages so I'm closing it.
